import Head from 'next/head'
import styles from '../styles/Home.module.css';

// import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>codeMunchers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">DNodes{'</>'}</a>
        </h1>

        <p className={styles.description}>Everything Decentralized<br />
          Get started by selecting a dapp
        </p>

        <div className={styles.grid}>
          <a href="/land" className={styles.card}>
            <h2>LandGister&rarr;</h2>
            <p>A DApp that registers land records on the blockchain</p>
          </a>

          <a href="https://decentratickets.netlify.app" className={styles.card}>
            <h2>Decentralized Smart Ticketing &rarr;</h2>
            <p>Connecting Event Hosts directly to Customers</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>DStorage &rarr;</h2>
            <p>Secure your files forever</p>
          </a>

          <a
            id="addapp"
            href="https://bit.ly/Dappsflow"
            className={styles.card}
          ><h2>Add <p>+</p></h2>
          </a>
        </div>
      </main>

    </div>
  )
}
